version: '3'
services:
  todofront:
    image: todofrontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    networks:
      - todonetwork

  todoback:
    image: todobackend
    ports:
      - "3001:3001"
    networks:
      - todonetwork

  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - todonetwork

networks:
  todonetwork:
