version: '3'
services:
  todoback:
    image: todobackend:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - todo-app-network

  todofront:
    image: todofrontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - todo-app-network

  todotests:
    image: todotests:latest
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - todo-app-network

networks:
  todo-app-network:
